header:
  version: 14

distro: poky
machine: qemux86-64

repos:
  # Main repository (this repository)
  meta-example:
    url: https://github.com/alfredomantilla/scratchpad.git
    refspec: main
    layers:
      .: excluded

  # Poky (base Yocto layer) - scarthgap release
  poky:
    url: https://git.yoctoproject.org/poky
    refspec: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  # OpenEmbedded meta-openembedded - scarthgap
  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded.git
    refspec: scarthgap
    layers:
      meta-oe:
      meta-python:
      meta-networking:

  # Example custom layer (if you have one on GitHub)
  # meta-custom:
  #   url: https://github.com/yourorg/meta-custom.git
  #   refspec: main
  #   layers:
  #     .:

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"
    BBPATH = "${TOPDIR}"
    BBFILES ?= ""

local_conf_header:
  standard: |
    CONF_VERSION = "2"
    PACKAGE_CLASSES = "package_rpm"
    SDKMACHINE = "x86_64"

  diskmon: |
    BB_DISKMON_DIRS ??= "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"

  debug-tweaks: |
    EXTRA_IMAGE_FEATURES = "debug-tweaks"

target:
  - core-image-minimal
